### PR TITLE
Swapped dark/light button icons fixed

### PR DESCRIPTION
**Pull request by igorakkerman**

### CODE REVIEW

**Comment by Leworoe** [comment]
Do you have any idea, why the icon on the dark theme isn´t right? The icon should be white. Everything should be fine with your commit, I´ve also looked in the [docu](https://webextension-api.thunderbird.net/en/91/messageDisplayAction.html#themeicons), but I have no clue why this isn´t work.
image

**Comment by igorakkerman** [comment]
The docomentation on https://webextension-api.thunderbird.net/en/78/messageDisplayAction.html#messagedisplayaction-themeicons says that `dark` refers to dark text with a light theme and `light` refers to light text with a dark theme. Indeed a bit confusing.

**Comment by Leworoe** [comment]
My problem is that the `light` icon is never used. I have loaded your branch in my thunderbird and tested it.

Light (good): image
Dark (bad): image

I want to understand why the `light` icon is never used.

**Comment by Leworoe** [comment]
I found a solution for this problem, I will detecting the theme in the js and change the icon from there.

**Pull request merged**
